apiVersion: platform.kratix.io/v1alpha1
kind: Destination
metadata:
  name: platform
  labels:
    environment: terraform
spec:
  path: tf-resources
  stateStoreRef:
    kind: GitStateStore
    name: default
